# This is only an example. Most values are dummy placeholders just to match the
# types; they are often not optimal and must be tuned.

[control]
version = 4
online = true

state_file = './models/mortal.pth'
best_state_file = './models/best.pth'
tensorboard_dir = './dir'

device = 'cuda:0'
enable_cudnn_benchmark = false
enable_amp = false
enable_compile = false